# Generated by Django 5.2.5 on 2025-09-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("ppg_green", models.JSONField()),
                ("ppg_ir", models.JSONField()),
                ("imu", models.JSONField()),
                ("predictions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
