# Generated by Django 5.2.6 on 2025-09-26 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="imu",
            new_name="acc",
        ),
        migrations.RenameField(
            model_name="sensordata",
            old_name="device_id",
            new_name="uuid",
        ),
    ]
