# Generated by Django 5.2.6 on 2025-09-26 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_imu_sensordata_acc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="uuid",
            new_name="device_id",
        ),
        migrations.RenameField(
            model_name="sensordata",
            old_name="acc",
            new_name="imu",
        ),
    ]
