# Generated by Django 5.2.6 on 2025-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_uuid_sensordata_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="ppg_red",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="ppg_green",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="ppg_ir",
            field=models.JSONField(default=list),
        ),
    ]
