# Generated by Django 5.2.6 on 2025-10-06 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_sensordata_ppg_red_alter_sensordata_ppg_green_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="imu",
        ),
    ]
